### PR TITLE
added in yaml support for cli target_format 

### PR DESCRIPTION
**Pull request by dfezzie**
Addresses last point in #12

### CODE REVIEW

**Comment by kurtbrose** [comment]
this looks good to me!

one thing I wonder about is using `extra_dependencies` to make `yaml` optional rather than a strict dependency (http://peak.telecommunity.com/DevCenter/setuptools#declaring-extras-optional-features-with-their-own-dependencies)

not sure if that is worth it in this case; it might also lead to confusing behavior if the `yaml` library was already pre-installed then `--format=yaml` will work even though the `[yaml]` feature was not installed

**Comment by kurtbrose** [comment]
(not saying do the extra dependencies thing, just it is worth everybody thinking about a little bit before we merge)

**Comment by dfezzie** [comment]
Thanks for the input @kurtbrose! 

I think that would make sense if the entire cli was installed using `extra_dependencies`. In that case, `yaml` and any further formats supported could be installed separately only when cli use is required

**Comment by mahmoud** [comment]
Code looks great! Those tests are appreciated.

Kurt's right in that YAML is a pretty heavy dependency for something not used in the core. What I was going to suggest was basically do a runtime import and then if one of pyyaml or ruamel yaml aren't available, print a message recommending installing it before processing with YAML. 

Note that yaml would stay in the requirements, as it's used for those tests, and you can feel free to include it in the test_requires part of setup.py as well.

Also, a quick question, by the by: do you plan on using the yaml functionality?

**Comment by dfezzie** [comment]
Hey guys, sorry about the delay. I have worked on it and pulled out the logic for handling the target into a new function `mw_handle_target`. I have also pulled out YAML into the `setup.py`

```python
extras_require = {
        'yaml':  ['PyYAML'],
},
```

Is there any way to test this addition?

**Comment by mahmoud** [comment]
@dfezzie Looks good! Thanks very much!

**Pull request merged**
