### PR TITLE
Add version attribute

### PR DESCRIPTION
**Pull request by P-Alban**
Solves #128

### CODE REVIEW

**Comment by mahmoud** [comment]
Hi @P-Alban! Thanks for the PR. I think we should probably tune the codecov to be less sensitive. 

As for this approach, it's new to me, would you mind providing some links/citations as to its conventionality? I'm used to doing things [this way](https://github.com/mahmoud/clastic/blob/df5aac0800e3629bce4377cd1b45c64909a8fd47/setup.py#L18) but I'm not attached if there's a better way.

Thanks in advance!

**Comment by P-Alban** [comment]
It's just an short and not quite flexible version of your version. But in this particular case it's good enough. 
This approach can gain some problems when for instance you're trying to fetch version of some underlying dependency, which is not installed. So it will raise. 

But in case of glom getting `__version__` attribute wouldn't be possible if glom isn't installed, so :)

**Comment by mahmoud** [comment]
After some discussion with a variety of other maintainers, I've come to the decision that the code should define the version that setup.py picks up, not the other way around. At least until we change to a package metadata strategy for which that won't be necessary/possible (e.g., PEP518 maybe).

If you could change this PR to something [like this](https://github.com/mahmoud/clastic/blob/df5aac0800e3629bce4377cd1b45c64909a8fd47/setup.py#L18), I'll happily and very thankfully merge it, otherwise, I'll probably change it myself.

**Comment by P-Alban** [comment]
Yeah, make sense, i'll do that.

**Comment by mahmoud** [comment]
Picture perfect :camera_flash:   Thanks for your patience and the code! Looking forward to the next :)

**Pull request merged**
