### PR TITLE
added Group

### PR DESCRIPTION
**Pull request by kurtbrose**

### CODE REVIEW

**Comment by mahmoud** [comment]
Nice, kinda like `partition`, eh? I guess group values have to be hashable then, right? First blush, I think the name is ok, just need to get a bit more coverage and maybe enhance the docs a bit. I'll re-review shortly, I hope (might check it out in the morning).

**Comment by kurtbrose** [comment]
yea, it came up organically when I was working on something in november

**Comment by kurtbrose** [comment]
codecov seems to be python 2 vs python 3 special casing -- not sure how they showed up as under test before

maybe needs #pragma no cover

**Comment by kurtbrose** [comment]
closing this in favor of Group mode

**Pull request closed without merging**
