### PR TITLE
Check

### PR DESCRIPTION
**Pull request by kurtbrose**
there are still a bunch of TODOs around the error behavior, but the basic functionality is working

### CODE REVIEW

**Comment by kurtbrose** [comment]
the CI failures are doc-tests which I haven't figure out how to get running locally

**Comment by kurtbrose** [comment]
updated to keep up with the big refactor

**Comment by mahmoud** [comment]
@kurtbrose fixed some stuff up and addressed several of the TODOs. commit messages mostly speak for themselves, let me know what you think!

**Comment by mahmoud** [comment]
This is pretty much ready to roll. That said, as mentioned in the TODOs of the code, I think the next gen of Check (besides adding more conditions and other enhancements), should make use of the Scope system to allow checking to continue until the last Check at that "level" in the spec.

Basically, we want to collect as many errors as possible before raising the exception. The main area for this would be peers in a `dict` spec. 

There would be some heuristics involved to keep from creating too many messages, of course, but I think the value and architecture are both definitely there.

**Pull request merged**
